apiVersion: v1
kind: Service
metadata:
  name: socks-proxy-svc
  labels:
    app: socks-proxy
spec:
  type: LoadBalancer
  loadBalancerIP: 192.0.2.127
  ports:
  - protocol: TCP
    port: 1080
    targetPort: 1080
  selector:
    app: socks-proxy
